In [1]:
import numpy as np

In [4]:
from numpy import genfromtxt
data = genfromtxt('../DATA/bank_note_data.txt', delimiter = ',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels = data[:, 4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:, 0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [10]:
print(len(X_train), len(X_test))

919 453


In [11]:
#standardize between 0 and 1 (normalization)

from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler = MinMaxScaler()

In [13]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [14]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
X_train.max()


1.0000000000000002

In [16]:
X_train.min()

0.0

In [17]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(4, input_dim = 4, activation = 'relu'))
model.add(Dense(8, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))


In [18]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [19]:
model.fit(X_train, y_train, epochs = 50, verbose = 2)

Epoch 1/50
 - 0s - loss: 0.6784 - acc: 0.5843
Epoch 2/50
 - 0s - loss: 0.6618 - acc: 0.6028
Epoch 3/50
 - 0s - loss: 0.6476 - acc: 0.6409
Epoch 4/50
 - 0s - loss: 0.6339 - acc: 0.6616
Epoch 5/50
 - 0s - loss: 0.6182 - acc: 0.6942
Epoch 6/50
 - 0s - loss: 0.6012 - acc: 0.7258
Epoch 7/50
 - 0s - loss: 0.5816 - acc: 0.7606
Epoch 8/50
 - 0s - loss: 0.5608 - acc: 0.8118
Epoch 9/50
 - 0s - loss: 0.5375 - acc: 0.8400
Epoch 10/50
 - 0s - loss: 0.5154 - acc: 0.8825
Epoch 11/50
 - 0s - loss: 0.4922 - acc: 0.8814
Epoch 12/50
 - 0s - loss: 0.4705 - acc: 0.8912
Epoch 13/50
 - 0s - loss: 0.4491 - acc: 0.8934
Epoch 14/50
 - 0s - loss: 0.4309 - acc: 0.8901
Epoch 15/50
 - 0s - loss: 0.4128 - acc: 0.8912
Epoch 16/50
 - 0s - loss: 0.3961 - acc: 0.8923
Epoch 17/50
 - 0s - loss: 0.3814 - acc: 0.8955
Epoch 18/50
 - 0s - loss: 0.3694 - acc: 0.8955
Epoch 19/50
 - 0s - loss: 0.3567 - acc: 0.8977
Epoch 20/50
 - 0s - loss: 0.3452 - acc: 0.8945
Epoch 21/50
 - 0s - loss: 0.3349 - acc: 0.8977
Epoch 22/50
 - 0s - lo

In [20]:
X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [21]:
#find the pred classes

model.predict_classes(X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [22]:
model.metrics_names

['loss', 'acc']

In [23]:
model.evaluate(X_test, y_test)

453/453 [==============================] - 0s 60us/step


[0.17068739434412247, 0.9492273730684326]

In [24]:
from sklearn.metrics import confusion_matrix, classification_report

In [25]:
predictions = model.predict_classes(X_test)

In [26]:
confusion_matrix(y_test, predictions)

array([[252,   5],
       [ 18, 178]])

In [27]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.93      0.98      0.96       257
        1.0       0.97      0.91      0.94       196

avg / total       0.95      0.95      0.95       453



In [28]:
#saving the model
model.save('sai_forge.h5')

In [29]:
from keras.models import load_model
model = load_model('sai_forge.h5')

In [30]:
model.predict_classes(X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    